@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.toblexson.minerology.dataproviders;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;