@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.toblexson.examplemod;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;